name:                myPrelude
version:             0.1.0.0
github:              "ssbothwell/myPrelude"
license:             BSD3
author:              "Solomon Bothwell"
maintainer:          "ssbothwell@gmail.com"
copyright:           "2019 Solomon Bothwell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/myPrelude#readme>

dependencies:
  - base >= 4.7 && < 5
  - ghc-prim
  - integer-gmp

library:
  source-dirs: src
  exposed-modules:
      - Data.BinaryTree
      - Data.BinaryTree.Type
      - Data.BinaryTree.Classes
      - Data.Bool
      - Data.Bool.Type
      - Data.Bool.Classes
      - Data.Bool.Extra
      - Data.Char
      - Data.Char.Type
      - Data.Char.Classes
      - Data.Const
      - Data.Const.Type
      - Data.Const.Classes
      - Data.Either
      - Data.Either.Type
      - Data.Either.Classes
      - Data.Function
      - Data.Free
      - Data.Free.Type
      - Data.Free.Classes
      - Data.Free.Effects
      - Data.Identity
      - Data.Identity.Type
      - Data.Identity.Classes
      - Data.List
      - Data.List.Type
      - Data.List.Classes
      - Data.List.Extra
      - Data.Maybe
      - Data.Maybe.Type
      - Data.Maybe.Classes
      - Data.NonEmpty
      - Data.NonEmpty.Type
      - Data.NonEmpty.Classes
      - Data.Ordering
      - Data.Ordering.Type
      - Data.Ordering.Classes
      - Data.Parser
      - Data.Parser.Type
      - Data.Parser.Classes
      - Data.Reader
      - Data.Reader.Type
      - Data.Reader.Classes
      - Data.State
      - Data.State.Type
      - Data.State.Classes
      - Data.State.Extra
      - Data.Store
      - Data.Store.Type
      - Data.Store.Classes
      - Data.Stream
      - Data.Stream.Type
      - Data.Stream.Classes
      - Data.String
      - Data.String.Type
      - Data.String.Classes
      - Data.Tree
      - Data.Tree.Type
      - Data.Tree.Classes
      - Data.Tuple
      - Data.Tuple.Type
      - Data.Tuple.Classes
      - Data.Void
      - Typeclasses.Alternative
      - Typeclasses.Alternative.Class
      - Typeclasses.Alternative.Extra
      - Typeclasses.Applicative
      - Typeclasses.Applicative.Class
      - Typeclasses.Applicative.Extra
      - Typeclasses.Arrow
      - Typeclasses.Bifunctor
      - Typeclasses.Category
      - Typeclasses.Comonad
      - Typeclasses.Contravariant
      - Typeclasses.Contravariant.Class
      - Typeclasses.Contravariant.Extra
      - Typeclasses.Eq
      - Typeclasses.Foldable
      - Typeclasses.Functor
      - Typeclasses.Functor.Class
      - Typeclasses.Functor.Extra
      - Typeclasses.IsList
      - Typeclasses.IsString
      - Typeclasses.Lens
      - Typeclasses.Monad
      - Typeclasses.Monad.Class
      - Typeclasses.Monad.Extra
      - Typeclasses.Monoid
      - Typeclasses.Monoid.Class
      - Typeclasses.Monoid.Extra
      - Typeclasses.Numerics
      - Typeclasses.Ord
      - Typeclasses.Profunctor
      # - Typeclasses.Rg
      # - Typeclasses.Rig
      # - Typeclasses.Rng
      # - Typeclasses.Ring
      - Typeclasses.Semigroup
      - Typeclasses.Semigroup.Class
      - Typeclasses.Semigroup.Extra
      - Typeclasses.Traversable
  default-extensions:
    - DeriveAnyClass
    - EmptyCase
    - FlexibleInstances
    - InstanceSigs
    - KindSignatures
    - LambdaCase
    - NoImplicitPrelude
    - RankNTypes
    - RebindableSyntax
    - StandaloneDeriving
    - ScopedTypeVariables
    - TypeSynonymInstances

tests:
  myPrelude-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - myPrelude
