name:                myPrelude
version:             0.1.0.0
github:              "ssbothwell/myPrelude"
license:             BSD3
author:              "Solomon Bothwell"
maintainer:          "ssbothwell@gmail.com"
copyright:           "2019 Solomon Bothwell"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/myPrelude#readme>

dependencies:
  - base >= 4.7 && < 5
  - ghc-prim
  - integer-gmp

library:
  source-dirs: src
  exposed-modules:
      - Data.BinaryTree
      - Data.Bool
      - Data.Const
      - Data.Either
      - Data.Function
      - Data.Free
      - Data.Identity
      - Data.List
      - Data.Maybe
      - Data.NonEmpty
      - Data.NonEmpty.Type
      - Data.Ordering
      - Data.Parser
      - Data.Reader
      - Data.State
      - Data.Store
      - Data.Stream
      - Data.String
      - Data.Tree
      - Data.Tuple
      - Typeclasses.Applicative
      - Typeclasses.Applicative.Class
      - Typeclasses.Applicative.Extra
      - Typeclasses.Alternative
      - Typeclasses.Arrow
      - Typeclasses.Bifunctor
      - Typeclasses.Category
      - Typeclasses.Comonad
      - Typeclasses.Eq
      - Typeclasses.Foldable
      - Typeclasses.Functor
      - Typeclasses.Functor.Class
      - Typeclasses.Functor.Extra
      - Typeclasses.Lens
      - Typeclasses.Monad
      - Typeclasses.Monad.Class
      - Typeclasses.Monad.Extra
      - Typeclasses.Monoid
      - Typeclasses.Numerics
      - Typeclasses.Ord
      - Typeclasses.Profunctor
      # - Typeclasses.Rg
      # - Typeclasses.Rig
      # - Typeclasses.Rng
      # - Typeclasses.Ring
      - Typeclasses.Semigroup
      - Typeclasses.Traversable
  default-extensions:
    - NoImplicitPrelude
    - InstanceSigs
    - ScopedTypeVariables
    - RankNTypes
    - KindSignatures
    - TypeSynonymInstances

tests:
  myPrelude-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base >=4.7 && <5
      - myPrelude
